version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

hooks:
  ApplicationStop:
    - location: stop_container.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: cleanup_old_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: start_container.sh
      timeout: 300
      runas: root
